### ISSUE TITLE
Bad gateway (502) error on localhost

### ISSUE THREAD

**Issue by pravesh-kasare** [g3w-suite/g3w-suite-docker#105]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-suite-docker/issues) and this bug has never been reported before

### Subject of the issue

![image](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/ef7125fd-5cd0-4a1e-9a14-d80a27351327)

### Steps to reproduce

1. configured the G3W suite using docker compose on win 11 os
2. step by step configured the files
3. after running `docker up -d`  and accessed the [localhost:8080](http://localhost:8080) web page displaced showing bad gate way instead of login page shown in readme file

### Environment

- g3w-admin: 3.6
- g3w-client: 3.8.6
- browser: MS edge
- operating system: Win 11 desktop

**Comment by pravesh-kasare** [comment]
![image](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/daba24f8-5a4b-4972-96f4-3ecb7ee84e94)
![image](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/ede54261-4776-46d7-9c6a-7eae287e73e3)

**Comment by Raruto** [comment]
Hi @pravesh-kasare

> https://github.com/g3w-suite/g3w-suite-docker/issues/105#issue-1815710281

The 502 (bad gateway) error is a bit more common when working with docker services.

Usually you just have to wait for the installation and/or starting of all services to finish completely.

Sometimes the server seems to be doing nothing special, so be very patient..

> https://github.com/g3w-suite/g3w-suite-docker/issues/105#issuecomment-1645535767

The docker container (which is a Linux OS) is trying to run windows-only compatible files.

Please try again after double checking line endings of your local files 👉 https://github.com/g3w-suite/g3w-suite-docker/issues/69

👋 Raruto

**Comment by pravesh-kasare** [comment]
hi,
after executing

```
docker-compose up -d
```

Post GIS is running but g3w suite exiting

however after executing

```
docker compose -f docker-compose-dev.yml up -d
```

Both post GIS and G3W suite exiting..

with error:

```
time="2023-07-24T17:37:14+05:30" level=warning msg="Found orphan containers ([g3w-suite-docker-certbot-1 g3w-suite-docker-redis-1 g3w-suite-docker-nginx-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
```

Also `--remove-orphans` unknown command.

![image](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/af63179e-c0c1-4290-b172-783ec478c3e8)

**Comment by pravesh-kasare** [comment]
and 502 bad gateway problem not solved

**Comment by pravesh-kasare** [comment]
![image](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/1e83b58e-67e0-494c-9344-c6f5019164e2)
![image](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/2505e748-d658-4e5d-8ebb-e5f7cf075c0e)
![image](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/5e8aabbf-bec1-4e34-8399-b6e0a20d9117)

**Comment by Raruto** [comment]
> https://github.com/g3w-suite/g3w-suite-docker/issues/105#issuecomment-1647831311
> https://github.com/g3w-suite/g3w-suite-docker/issues/105#issuecomment-1647832672
> https://github.com/g3w-suite/g3w-suite-docker/issues/105#issuecomment-1647834661

First of all, please don't use this platform not as a chat (think before posting, then post one comment at a time..).

As I've pointed out here 👉 https://github.com/g3w-suite/g3w-suite-docker/issues/102#issuecomment-1635829116, **reporting to others your steps-by-step (in a detailed manner) is crucial to understanding what is going wrong**.

---

> 502 bad gateway problem not solved

Overall, it's not clear what you're trying to achive since you're mixing docker **development configs**:

```sh
docker compose -f docker-compose-dev.yml up -d
```

with **production configs**:

```sh
docker-compose up -d
```

The 502 page is just an informational message and is only shown in the production version (**when you work with docker containers you should think of it as the equivalent of a "maintenance page"**).

You should investigate server logs further if you suspect more serious problems.

Ultimately, I advise you to read again (and more carefully) all the **necessary steps to follow to start working with docker in [here](https://github.com/g3w-suite/g3w-client/blob/dev/README.md) and [here](https://github.com/g3w-suite/g3w-suite-docker/blob/dev/README_DEV.md)**.

If you're new to docker, please have a look at dedicated support forums like [stackoverflow.com](https://stackoverflow.com/) for any additional help and information. 

👋 Raruto
