### ISSUE TITLE
Еrror on nginix: 502 Bad Gateway!!! what am I missing?

### ISSUE THREAD

**Issue by nstoykov** [g3w-suite/g3w-suite-docker#13]
Hello,
I try to install G3W docker again and whatever attempts I make it always leads to an error I always get an error on nginix: 502 Bad Gateway
I use Ubuntu Server 18.04.5 (hostname: g3w-suite.demo) with SSH installed on it, git version 2.17.1, Docker version 19.03.12
  
Here are the commands I use to install g3w-suite:

cd home
git clone https://github.com/g3w-suite/g3w-suite-docker.git --branch v3.0.x
cd g3w-suite-docker
docker build -f Dockerfile.g3wsuite-deps.ltr.dockerfile -t g3wsuite/g3w-suite-deps:latest --no-cache .
docker build -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite-dev:latest --no-cache .
docker-compose up -d

The changes I make to .env are as follows

![image](https://user-images.githubusercontent.com/3955547/92534317-1d7ed680-f23d-11ea-8db7-027c2e464a31.png)

As well as the lines in: /config/nginx/django.conf

server g3w-suite.demo:8000;

server_name g3w-suite.demo;

Can you advise me when I mess with installation ???

**Comment by nislamnreca** [comment]
Hello.
I think you pubic host name 'g3w-suite.demo' is not reachable. You can try with IP address of your public host.
Good luck!!
Thanks

**Comment by wlorenzetti** [comment]
Hi the problem is not the host name, but _G3WSUITE_POSTGRES_HOST,_ if you set this env var to a localhost you are telling to docker compose to use a PostgreSql instance inside g3w_suite container, but if you watch to docker-compose.yml you can see that there is a postgresql/postgis image use for it, so if you don't want use a your owner PostgreSql/Postgis instace leave _G3WSUITE_POSTGRES_HOST_ to `postgis`.
Try it if _"bad gateway"_ persist, please upload her your docker logs.
