### ISSUE TITLE
Please explain how to "refresh" the code from github 

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-suite-docker#15]
Hello,

I am using the _dev version of g3wsuite in the docker.
When I restart the docker container, it doesn't update the code from github.
How can I "refresh" it? Can you write it in the documentation?

Thank you!

**Comment by wlorenzetti** [comment]
Hi @lucamanga, first of all I suggest you to use branch v3.0.x of this repository , this is the last stable version.
In particular I suggest you to re-build your images because the images on docker hub are not update to latest code/branch.
https://github.com/g3w-suite/g3w-suite-docker#g3w-suite
In particular build first g3w-suite-deps image and next g3w-suite-dev image.

A the momente the g3w-suite code is inside g3w-suuite-dev image.. so for update the code you've to re-build the image. For to do this I use this simple bash script `update_deploy.sh`:
```bash
#!/bin/bash

docker-compose -f docker-compose-certs.yml down
docker build -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite-dev:latest>
docker-compose -f docker-compose-certs.yml up -d
```
I follow your suggestion and in the next days I'll update the documentation :).

**Comment by lucamanga** [comment]
Thank you
