### ISSUE TITLE
problem with named volume in docker-compose.yml

### ISSUE THREAD

**Issue by zanollim** [g3w-suite/g3w-suite-docker#32]
Version 3.2.x

if I use the internal docker volume, as suggested in the .env file:
```
# Shared volume mount (docker internal: shared-volume)
WEBGIS_DOCKER_SHARED_VOLUME=shared-volume 
```

I cannot build the suite because the following error:
```
docker-compose up -d
ERROR: Named volume "shared-volume/node_modules:/code/node_modules:rw" is used in service "g3w-suite" but no declaration was found in the volumes section.
```

I suspect that you cannot specify subfolders in named volumes, like shared-volume/node_modules:something_else
but only: shared-volume:something_else
Can you confirm?

(complimenti per il lavoro eccezionale!)

**Comment by wlorenzetti** [comment]
Hi @zanollim, 
the env var WEBGIS_DOCKER_SHARED_VOLUME set a local folder where to save permanent data i.e. database data cluster, qgis projects etcetera...
So i.e. try to set this env to a value as "/home/<your_home_name>/data-g3w-suite", I suggest you to not use path woth "/tmp" folder because every time you switch off the machine "/tmp" folder is erased.

**Comment by zanollim** [comment]
Thanks @wlorenzetti,

absolutely clear, I'll point out only that in docker-compose.yml you are declaring:

```
volumes:
  shared-volume:
```

but effectively you cannot use it as 'shared-volume' for the g3w-suite-docker

**Comment by wlorenzetti** [comment]
@zanollim grazie per i complimenti :)
