### ISSUE TITLE
arm docker image?

### ISSUE THREAD

**Issue by dncpax** [g3w-suite/g3w-suite-docker#87]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-suite-docker/issues) to make sure this feature hasn't been requested already.

### Motivation

I was trying h3w and got stuck since there's no support for arm arch...

I'm asking bc I'm using the free tier oracle vps - `4vcpu, 24gb ram, and 200gb disk`. It's really impressive, so I've been consolidating a few tools and services here.

Maybe you'd consider making a docker image for arm?

Thanks.

### Suggested solution

Maybe you'd consider making a docker image for arm?

**Comment by Raruto** [comment]
Hi @dncpax,

thank you for letting us know about the capabilities of [Oracle Cloud](https://www.oracle.com/cloud/free/).

As far as I'm concerned (as things stand right now in **v3.5**), I think there are way too many Dockerfiles in this repository to maintain and that they should at least be unified in the first place (ref: https://github.com/g3w-suite/g3w-suite-docker/pull/79). Either way, I too welcome creating a less resource-intensive stack.

BTW, since I don't think any of us have previous experience with [buildx](https://www.docker.com/blog/multi-arch-images/), if you could submit a pull request about it (eg. updating the [README.md](https://github.com/g3w-suite/g3w-suite-docker/blob/dev/README.md) file with the steps you think that could be necessary to build and deploy the ARM image) it might help everyone make a more complete idea and discuss it with you accordingly

_Have a nice day,
Raruto_

**Comment by dncpax** [comment]
hey @Raruto. I've never built a docker file to be honest... but maybe it's just a matter of adjusting images to their arm versions, as long as they exist. For instance, if there's an apache image, then it'd be pointed to the arm image.
Anyway, I'll see if I can make a 1st try.

**Comment by wlorenzetti** [comment]
I close this issue for inactivity.
