### ISSUE TITLE
Block in installation

### ISSUE THREAD

**Issue by abrousseau89** [g3w-suite/g3w-suite-docker#94]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

Hello, 

I am stuck in the installation by following the documentation

on the line : 

_set database, media root and session cookies name:_

```py
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': '<db_name>',
        'USER': '<db_user>',
        'PASSWORD': '<db_user_password>',
        'HOST': '<db_host>',
        'PORT': '<db_port>',
    }
}

...

DATASOURCE_PATH = '<static_path_to_gis_data_source>'

...

MEDIA_ROOT = '<path_to_media_root>'

...

SESSION_COOKIE_NAME = '<unique_session_i`
```

I don't know what to put in the variables?

so i took this version : 

[g3w-suite-docker/g3w-suite/settings_docker.py](https://github.com/g3w-suite/g3w-suite-docker/blob/9475d8260979309e9e583a951306326b016247ea/config/g3w-suite/settings_docker.py)

i copy past all after the line : 

```py
G3WADMIN_PROJECT_APPS = []
```

but after i can't use paver install

```
Build failed: Unknown task: install
```

Thanks

### Suggested solution

i install paver ...

and after i have a paver directory in `home/user/g3w-admin/g3w-admin/base/settings/`

Did I miss something ?

**Comment by wlorenzetti** [comment]
Hi @abrousseau89, for deploy (and/or use for developing) I suggest you docker version of G3W-SUITE: https://github.com/g3w-suite/g3w-suite-docker try to follow the READ instruction.

Your message is a bit confusing because it is not clear whether you are using the stand alone version or the dockerized version since you mention `settings_docker.py`.

I'll move this issue to https://github.com/g3w-suite/g3w-suite-docker repository.

**Comment by abrousseau89** [comment]
I completely reinstalled the server as well as Docker and Docker-Compose then did the installation and everything worked.

Thanking you.
